PreCommit:
  CustomScript:
    enabled: true
    description: 'Run CI script'
    required_executable: './scripts/cibuild'
  BundleCheck:
    enabled: true
  ExecutePermissions:
    enabled: true
    exclude: 'scripts/*'
  Mdl:
    enabled: true
  TrailingWhitespace:
    enabled: true
    exclude:
      - 'assets/fonts/fontawesome-webfont.svg'
      - 'assets/themes/bootstrap/resources/bootstrap/fonts/glyphicons-halflings-regular.svg'
