dist: trusty
sudo: false # route your build to the container-based infrastructure for a faster build

language: ruby

rvm:
- 2.4.0

script: ./scripts/cibuild

cache:
  bundler: true
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
