#!/usr/bin/env bash

set -e # halt script on error

bundle exec jekyll build

bundle exec htmlproofer \
  --alt-ignore /images/HtL_Banner.svg \
  --assume-extension \
  --check-external-hash \
  --check-html \
  --empty-alt-ignore \
  --report-missing-names \
  --report-script-embeds \
  --url-ignore https://apps.twitter.com/app/new,http://wikis.olin.edu/linux/doku.php,http://127.0.0.1:5000 \
  ./_site

# These external links are ignored:
# - 127.0.0.1 is an example; it works when the student is following the setup instructions
# - apps.twitter.com works when signed into Twitter
# - wikis.olin.edu only works inside the Olin intranet

# These external hashes are expected to fail, because they don't
# name internal anchors but are instead parsed by the page script.
# - https://docs.google.com/.../edit#gid=0
# - https://packagecontrol.io/installation#st3
# - http://www.ndpsoftware.com/git-cheatsheet.html#loc=workspace;
